// timer-dashboard: pure cron task scheduler UI
// CJS module. Returns full HTML page.
// API: GET/POST /api/cron/tasks, PUT/DELETE /api/cron/tasks/:id, POST /api/cron/tasks/:id/run

function render() {
  return '<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>定时任务</title>\n<style>\n' +
    css() +
    '\n</style>\n</head>\n<body>\n' +
    html() +
    '\n<script>\n' +
    js() +
    '\n</script>\n</body>\n</html>';
}

function css() {
  return [
    ':root{',
    '  --bg:#fafaf9; --card:#fff; --border:#e7e5e4;',
    '  --accent:#b8804a; --accent-hover:#c9955e;',
    '  --text:#1c1917; --text2:#78716c; --text3:#a8a29e;',
    '  --on:#059669; --off-bg:#f5f5f4;',
    '  --fail:#dc2626; --once:#d97706; --running:#2563eb;',
    '  --font:system-ui,-apple-system,"Noto Sans SC",sans-serif;',
    '  --mono:"JetBrains Mono","Consolas",monospace;',
    '  font-family:var(--font); color:var(--text); background:var(--bg)',
    '}',
    '*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}',
    'body{min-height:100vh}',
    '/* header */',
    '.hd{padding:20px 28px 16px;background:var(--card);border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}',
    '.hd-left h1{font-size:22px;font-weight:600;letter-spacing:-.01em}',
    '.hd-left p{font-size:12px;color:var(--text3);margin-top:2px}',
    '.hd-right{display:flex;align-items:center;gap:14px}',
    '.hd-stat{font-size:12px;color:var(--text3)}',
    '.hd-stat b{font-weight:600;color:var(--text)}',
    '.hd-stat.on b{color:var(--on)}',
    '.hd-stat.off b{color:var(--text3)}',
    '.btn-add{padding:8px 18px;background:var(--accent);color:#fff;border:none;border-radius:6px;font-size:13px;cursor:pointer;display:inline-flex;align-items:center;gap:5px;white-space:nowrap;font-family:var(--font);font-weight:500}',
    '.btn-add:hover{background:var(--accent-hover)}',
    '/* card grid */',
    '.main{max-width:1100px;margin:0 auto;padding:24px}',
    '.card-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:16px}',
    '/* card */',
    '.tcard{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:18px 20px;display:flex;flex-direction:column;gap:12px;position:relative;overflow:hidden;transition:box-shadow .15s}',
    '.tcard:hover{box-shadow:0 2px 12px rgba(0,0,0,.06)}',
    '.tcard::before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--border)}',
    '.tcard.on::before{background:var(--on)}',
    '.tcard.once::before{background:var(--once)}',
    '.tcard.off::before{background:var(--text3)}',
    '.tcard.fail::before{background:var(--fail)}',
    '.tcard.off{background:var(--off-bg);opacity:.7}',
    '.tc-top{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}',
    '.tc-icon{font-size:20px;line-height:1;flex-shrink:0}',
    '.tc-badges{display:flex;gap:5px;flex-wrap:wrap}',
    '.badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:10px;font-weight:500;line-height:1.4}',
    '.badge-on{background:#ecfdf5;color:var(--on)}',
    '.badge-off{background:var(--off-bg);color:var(--text3)}',
    '.badge-once{background:#fffbeb;color:var(--once)}',
    '.badge-fail{background:#fef2f2;color:var(--fail)}',
    '.tc-name{font-size:15px;font-weight:600;line-height:1.3;word-break:break-word}',
    '.tc-desc{font-size:11px;color:var(--text3);line-height:1.4;word-break:break-word}',
    '.tc-desc:empty{display:none}',
    '.tc-sched{font-size:12px;color:var(--text2);line-height:1.4}',
    '.tc-sched strong{color:var(--text);font-weight:500}',
    '.tc-next{font-size:11px;color:var(--text3)}',
    '.tc-next span{font-family:var(--mono);color:var(--text2)}',
    '.tc-last{font-size:10px;color:var(--text3);display:flex;align-items:center;gap:4px}',
    '.tc-last .dot{width:6px;height:6px;border-radius:50%;flex-shrink:0}',
    '.dot-success{background:var(--on)}',
    '.dot-fail{background:var(--fail)}',
    '.dot-timeout{background:#f59e0b}',
    '.dot-running{background:var(--running);animation:pulse 2s infinite}',
    '@keyframes pulse{0%,100%{opacity:1}50%{opacity:.3}}',
    '.tc-actions{display:flex;gap:4px;flex-wrap:wrap}',
    '.btn-card{padding:4px 10px;border:1px solid var(--border);border-radius:5px;background:var(--card);font-size:11px;cursor:pointer;color:var(--text2);font-family:var(--font);display:inline-flex;align-items:center;gap:3px;transition:all .1s}',
    '.btn-card:hover{border-color:var(--accent);color:var(--accent)}',
    '.btn-card.go{background:var(--accent);color:#fff;border-color:var(--accent);font-weight:500}',
    '.btn-card.go:hover{background:var(--accent-hover)}',
    '.btn-card.del{color:var(--fail);border-color:transparent}',
    '.btn-card.del:hover{background:#fef2f2}',
    '/* empty */',
    '.empty{grid-column:1/-1;padding:64px 20px;text-align:center;color:var(--text3)}',
    '.empty-icon{font-size:40px;opacity:.2;margin-bottom:12px}',
    '.empty-title{font-size:15px;font-weight:500;color:var(--text2);margin-bottom:6px}',
    '.empty-desc{font-size:12px}',
    '/* overlay */',
    '.overlay{display:none;position:fixed;inset:0;background:rgba(28,25,23,.3);z-index:100;align-items:center;justify-content:center}',
    '.overlay.show{display:flex}',
    '.form-box{background:var(--card);width:480px;max-height:88vh;overflow-y:auto;border-radius:12px;box-shadow:0 12px 48px rgba(0,0,0,.15)}',
    '.form-head{padding:18px 22px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;background:var(--card);z-index:1}',
    '.form-head h3{font-size:16px;font-weight:600}',
    '.form-close{background:none;border:none;font-size:22px;cursor:pointer;color:var(--text3);line-height:1;padding:0 4px}',
    '.form-close:hover{color:var(--text)}',
    '.form-body{padding:22px}',
    '.fg{margin-bottom:18px}',
    '.fl{display:block;font-size:11px;font-weight:600;color:var(--text2);margin-bottom:5px;letter-spacing:.02em}',
    '.fhint{font-size:10px;color:var(--text3);margin-top:3px;line-height:1.4}',
    '/* presets */',
    '.preset-row{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}',
    '.preset-btn{padding:6px 14px;border:1px solid var(--border);border-radius:16px;background:var(--card);font-size:12px;cursor:pointer;color:var(--text2);font-family:var(--font);transition:all .12s;line-height:1}',
    '.preset-btn:hover{border-color:var(--accent);color:var(--accent)}',
    '.preset-btn.sel{background:var(--accent);border-color:var(--accent);color:#fff}',
    '.sub-row{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}',
    '.sub-btn{padding:5px 12px;border:1px solid var(--border);border-radius:14px;background:var(--bg);font-size:11px;cursor:pointer;color:var(--text2);font-family:var(--font);transition:all .12s}',
    '.sub-btn:hover{border-color:var(--accent);color:var(--accent)}',
    '.sub-btn.sel{background:var(--accent);border-color:var(--accent);color:#fff}',
    '.time-row{display:flex;align-items:center;gap:8px;margin-bottom:10px}',
    '.time-inp{width:56px;padding:5px 8px;border:1px solid var(--border);border-radius:5px;font-size:13px;text-align:center;font-family:var(--font);background:var(--bg);outline:none}',
    '.time-inp:focus{border-color:var(--accent);background:var(--card)}',
    '.interval-row{display:flex;align-items:center;gap:8px;margin-bottom:10px}',
    '.fi{width:100%;padding:8px 12px;border:1px solid var(--border);border-radius:6px;font-size:13px;font-family:var(--font);color:var(--text);outline:none;background:var(--bg)}',
    '.fi:focus{border-color:var(--accent);background:var(--card)}',
    '.fi.mono{font-family:var(--mono);font-size:12px}',
    'textarea.fi{resize:vertical;min-height:70px}',
    '.frow{display:flex;gap:10px}',
    '.frow .fg{flex:1}',
    '.sel-unit{font-size:12px;padding:5px 10px;border:1px solid var(--border);border-radius:5px;background:var(--bg);cursor:pointer;font-family:var(--font);color:var(--text2)}',
    '.sel-unit:focus{outline:none;border-color:var(--accent)}',
    '/* checkbox grids for custom cron */',
    '.cb-field{margin-bottom:12px}',
    '.cb-label{font-size:11px;font-weight:600;color:var(--text2);margin-bottom:4px}',
    '.cb-grid{background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:8px 10px}',
    '.cb-quick{display:flex;gap:5px;margin-bottom:8px;flex-wrap:wrap}',
    '.cbq-btn{padding:3px 10px;border:1px solid var(--border);border-radius:10px;background:var(--card);font-size:10px;cursor:pointer;color:var(--text2);font-family:var(--font);transition:all .12s}',
    '.cbq-btn:hover{border-color:var(--accent);color:var(--accent);background:#fdf8f4}',
    '.cb-items{display:flex;flex-wrap:wrap;gap:0}',
    '.cb-months{display:grid;grid-template-columns:repeat(4,1fr);gap:2px}',
    '.cb-dom{display:grid;grid-template-columns:repeat(7,1fr);gap:2px}',
    '.cb-dow{display:grid;grid-template-columns:repeat(7,1fr);gap:2px}',
    '.cbi{display:flex;align-items:center;justify-content:center;cursor:pointer}',
    '.cbi input{display:none}',
    '.cbi span{display:flex;align-items:center;justify-content:center;width:100%;padding:5px 0;font-size:11px;border-radius:4px;color:var(--text3);transition:all .12s;user-select:none}',
    '.cbi span:hover{background:var(--border);color:var(--text)}',
    '.cbi input:checked + span{background:var(--accent);color:#fff;font-weight:500}',
    '.cb-dom .cbi span{font-family:var(--mono);font-size:10px;padding:6px 0}',
    '.cb-hint{font-size:10px;color:var(--once);margin-top:4px}',
    '/* toggle */',
    '.toggle{display:flex;align-items:center;gap:8px;cursor:pointer;margin-top:6px}',
    '.toggle input{display:none}',
    '.toggle-track{width:36px;height:21px;border-radius:11px;background:var(--border);position:relative;transition:background .2s;flex-shrink:0}',
    '.toggle-track.on{background:var(--on)}',
    '.toggle-track::after{content:"";position:absolute;top:2px;left:2px;width:17px;height:17px;border-radius:50%;background:#fff;transition:transform .2s}',
    '.toggle-track.on::after{transform:translateX(15px)}',
    '.toggle-label{font-size:12px;color:var(--text3)}',
    '/* form footer */',
    '.fbtns{display:flex;gap:8px;justify-content:flex-end;margin-top:20px;padding-top:18px;border-top:1px solid var(--border)}',
    '.btn-cancel{padding:8px 20px;border:1px solid var(--border);background:var(--card);border-radius:6px;font-size:13px;cursor:pointer;color:var(--text2);font-family:var(--font)}',
    '.btn-cancel:hover{background:var(--bg)}',
    '.btn-submit{padding:8px 20px;background:var(--accent);color:#fff;border:none;border-radius:6px;font-size:13px;cursor:pointer;font-family:var(--font);font-weight:500}',
    '.btn-submit:hover{background:var(--accent-hover)}',
    '/* once mode */',
    '.once-mode-row{display:flex;gap:16px;margin-bottom:10px}',
    '.once-mode-row label{font-size:12px;color:var(--text2);cursor:pointer;display:flex;align-items:center;gap:5px}',
    '.once-mode-row input[type=radio]{accent-color:var(--once)}',
    '/* confirm */',
    '.cfm-overlay{display:none;position:fixed;inset:0;background:rgba(28,25,23,.3);z-index:200;align-items:center;justify-content:center}',
    '.cfm-overlay.show{display:flex}',
    '.cfm-box{background:var(--card);padding:28px;border-radius:12px;text-align:center;max-width:340px;box-shadow:0 12px 48px rgba(0,0,0,.15)}',
    '.cfm-box p{font-size:14px;color:var(--text2);margin-bottom:16px}',
    '.cfm-box .fbtns{justify-content:center;border:none;padding:0;margin:0}',
    '@media(max-width:640px){',
    '  .main{padding:16px}',
    '  .card-grid{grid-template-columns:1fr}',
    '  .form-box{width:94vw;max-height:92vh}',
    '  .hd{padding:14px 16px}',
    '}',
    '/* detail overlay */',
    '.detail-box{width:90vw;max-width:640px}',
    '.detail-box .form-head{border-bottom:1px solid var(--border)}',
    '.detail-body{padding:22px;max-height:70vh;overflow-y:auto}',
    '.detail-meta{font-size:12px;color:var(--text2);margin-bottom:14px;line-height:1.6}',
    '.detail-meta strong{color:var(--text);font-size:15px;display:block;margin-bottom:2px}',
    '.detail-prompt{background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:14px 16px;font-family:var(--mono);font-size:12px;line-height:1.7;white-space:pre-wrap;word-break:break-word;max-height:50vh;overflow-y:auto;color:var(--text)}',
    '::-webkit-scrollbar{width:4px}',
    '::-webkit-scrollbar-thumb{background:var(--border);border-radius:2px}',
    '/* disaster recovery panel */',
    '.dr-panel{max-width:1100px;margin:32px auto 0;padding:0 24px 32px}',
    '.dr-title{font-size:15px;font-weight:600;margin-bottom:4px}',
    '.dr-sub{font-size:11px;color:var(--text3);margin-bottom:14px}',
    '.dr-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px}',
    '.dr-card{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:14px 16px}',
    '.dr-card-head{font-size:12px;font-weight:600;margin-bottom:6px;color:var(--text)}',
    '.dr-card-body{font-size:11px;color:var(--text2);line-height:1.7}',
    '.dr-card-body code{font-family:var(--mono);font-size:10px;background:var(--bg);padding:1px 5px;border-radius:3px;word-break:break-all}',
    '.dr-card-body a{color:var(--accent)}'
  ].join('\n');
}

function html() {
  return [
    '<div class="hd">',
    '  <div class="hd-left">',
    '    <h1>定时任务</h1>',
    '    <p>卡片式管理 · 人和 AI 共享调度</p>',
    '  </div>',
    '  <div class="hd-right">',
    '    <span class="hd-stat on">活跃 <b id="n-on">0</b></span>',
    '    <span class="hd-stat off">停用 <b id="n-off">0</b></span>',
    '    <span class="hd-stat" style="opacity:.5" id="tick"></span>',
    '    <button class="btn-add" id="btn-add">+ 新建任务</button>',
    '  </div>',
    '</div>',
    '<div class="main">',
    '  <div class="card-grid" id="card-grid">',
    '    <div class="empty"><div class="empty-icon">&#9200;</div><div class="empty-title">暂无定时任务</div><div class="empty-desc">点击右上角「新建任务」创建第一个定时规则</div></div>',
    '  </div>',
    '  <!-- disaster recovery panel -->',
    '  <div class="dr-panel">',
    '    <div class="dr-title">容灾手册</div>',
    '    <div class="dr-sub">个人电脑一定会睡眠。方案围绕「错过就补」设计。</div>',
    '    <div class="dr-grid">',
    '      <div class="dr-card">',
    '        <div class="dr-card-head">电脑睡眠错过定时</div>',
    '        <div class="dr-card-body"><b>自动补偿已启用：</b>醒来后调度器检测到错过窗口，自动按链式顺序补跑最早错过的任务。<br>如仍失败：手动 <code>claude -p --model deepseek-v4-pro -- "执行XX日报..."</code></div>',
    '      </div>',
    '      <div class="dr-card">',
    '        <div class="dr-card-head">开机后没自动启动</div>',
    '        <div class="dr-card-body"><code>Start-Process node -ArgumentList "C:\\Users\\Administrator\\.agentboard\\server.js" -WindowStyle Hidden</code></div>',
    '      </div>',
    '      <div class="dr-card">',
    '        <div class="dr-card-head">任务到点没触发</div>',
    '        <div class="dr-card-body">1. <a href="/api/cron/health" target="_blank">健康检查</a> 看哪项红了<br>2. 查 <code>~/.agentboard/cron/scheduler-state.json</code> 重试是否满<br>3. 查 <code>~/.agentboard/cron/runtime-events.jsonl</code></div>',
    '      </div>',
    '      <div class="dr-card">',
    '        <div class="dr-card-head">完整手册</div>',
    '        <div class="dr-card-body"><code>~/.agentboard/cron/MAINTENANCE.md</code><br>含故障模型、恢复流程、日志位置、配置修改</div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '</div>',
    '<!-- form overlay -->',
    '<div class="overlay" id="form-overlay">',
    '  <div class="form-box">',
    '    <div class="form-head">',
    '      <h3 id="form-title">新建任务</h3>',
    '      <button class="form-close" id="form-close-btn">&times;</button>',
    '    </div>',
    '    <div class="form-body" id="form-body"></div>',
    '  </div>',
    '</div>',
    '<!-- confirm overlay -->',
    '<div class="cfm-overlay" id="cfm-overlay">',
    '  <div class="cfm-box">',
    '    <p>确定删除此任务？</p>',
    '    <div class="fbtns">',
    '      <button class="btn-cancel" id="cfm-cancel-btn">取消</button>',
    '      <button class="btn-submit" id="cfm-del-btn" style="background:#dc2626">确认删除</button>',
    '    </div>',
    '  </div>',
    '</div>',
    '<!-- detail overlay -->',
    '<div class="overlay" id="detail-overlay">',
    '  <div class="form-box detail-box">',
    '    <div class="form-head">',
    '      <h3 id="detail-title">提示词</h3>',
    '      <button class="form-close" id="detail-close-btn">&times;</button>',
    '    </div>',
    '    <div class="detail-body" id="detail-body"></div>',
    '  </div>',
    '</div>'
  ].join('\n');
}

function js() {
  return [
    'var API = "/api/cron";',
    'var tasks = [];',
    'var editingTask = null;',
    'var confirmDeleteId = null;',
    'var DAY_NAMES = ["周日","周一","周二","周三","周四","周五","周六"];',
    'var DAY_KEYS = [0,1,2,3,4,5,6];',
    '',
    '// --- utils ---',
    'function esc(s) { return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }',
    'function escAttr(s) { return String(s||"").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }',
    'function fmt(s) { if (!s) return "-"; try { var d=new Date(s+(s.indexOf("Z")>=0?"":"Z")); return d.toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}); } catch(e){return s;} }',
    '',
    '// --- cron human preview ---',
    'var MONTH_NAMES = ["","1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"];',
    'var DOW_NAMES = ["周日","周一","周二","周三","周四","周五","周六"];',
    '',
    'function fieldToList(val) {',
    '  if (!val || val === "*") return [];',
    '  var result = [];',
    '  var parts = val.split(",");',
    '  for (var i = 0; i < parts.length; i++) {',
    '    var p = parts[i];',
    '    if (p.indexOf("-") >= 0) {',
    '      var r = p.split("-");',
    '      for (var j = parseInt(r[0],10); j <= parseInt(r[1],10); j++) result.push(j);',
    '    } else {',
    '      result.push(parseInt(p,10));',
    '    }',
    '  }',
    '  return result;',
    '}',
    '',
    'function listToHuman(list, labels) {',
    '  if (!list.length) return "";',
    '  return list.map(function(v){ return labels ? labels[v] : v; }).join("、");',
    '}',
    '',
    'function cronToHuman(expr) {',
    '  if (!expr) return "";',
    '  var parts = expr.trim().split(/\\s+/);',
    '  if (parts.length !== 5) return expr;',
    '  var min = parts[0], hour = parts[1], dom = parts[2], month = parts[3], dow = parts[4];',
    '  var h = parseInt(hour,10), m = parseInt(min,10);',
    '  var ts = String(h).padStart(2,"0") + ":" + String(m).padStart(2,"0");',
    '',
    '  // Daily: * * * * *',
    '  if (dom === "*" && month === "*") {',
    '    if (dow === "*") return "每天 " + ts;',
    '    if (dow === "1-5") return "工作日 " + ts;',
    '    if (/^[0-7]$/.test(dow)) return "每" + DOW_NAMES[parseInt(dow)%7] + " " + ts;',
    '    var dowList = fieldToList(dow);',
    '    if (dowList.length) return "每周" + listToHuman(dowList, DOW_NAMES) + " " + ts;',
    '  }',
    '',
    '  // Interval: */N and 0 */N',
    '  if (/^\\*\\/\\d+$/.test(min) && hour === "*" && dom === "*" && month === "*" && dow === "*")',
    '    return "每" + parseInt(min.split("/")[1]) + " 分钟";',
    '  if (min === "0" && /^\\*\\/\\d+$/.test(hour) && dom === "*" && month === "*" && dow === "*")',
    '    return "每" + parseInt(hour.split("/")[1]) + " 小时";',
    '',
    '  // Month-constrained patterns',
    '  if (month !== "*") {',
    '    var mList = fieldToList(month);',
    '    var mh = listToHuman(mList, MONTH_NAMES);',
    '',
    '    // Month + specific day(s) + any DOW',
    '    if (dom !== "*" && dow === "*") {',
    '      var dList = fieldToList(dom);',
    '      // Quarterly: 1,4,7,10 + day 1',
    '      if (month === "1,4,7,10" && dom === "1") return "每季度第1天 " + ts;',
    '      // Semiannual: 1,7 + day 1',
    '      if (month === "1,7" && dom === "1") return "每半年第1天 " + ts;',
    '      // Single month + single day → "每年3月15日 09:00"',
    '      if (mList.length === 1 && dList.length === 1)',
    '        return "每年" + mh + dList[0] + "日 " + ts;',
    '      // Multiple months + single day → "每年1月1日、7月1日 09:00"',
    '      if (mList.length > 1 && dList.length === 1)',
    '        return "每年" + mList.map(function(mo){ return MONTH_NAMES[mo] + dList[0] + "日"; }).join("、") + " " + ts;',
    '      // Generic: month + day',
    '      if (dList.length === 1) return mh + "第" + dList[0] + "天 " + ts;',
    '      return mh + " " + listToHuman(dList).split(",").join("、") + "日 " + ts;',
    '    }',
    '',
    '    // Month + any day + specific DOW',
    '    if (dom === "*" && dow !== "*") {',
    '      var dowList = fieldToList(dow);',
    '      var dwh = listToHuman(dowList, DOW_NAMES);',
    '      if (mList.length === 1) return mh + " 每" + dwh + " " + ts;',
    '      return mh + " 每" + dwh + " " + ts;',
    '    }',
    '',
    '    // Month + any day + any DOW → "X月 每天 HH:MM"',
    '    if (dom === "*" && dow === "*") return mh + " 每天 " + ts;',
    '  }',
    '',
    '  // Day-of-month only (no month constraint)',
    '  if (dom !== "*" && month === "*" && dow === "*") {',
    '    if (/^\\d+$/.test(dom)) return "每月" + parseInt(dom) + "日 " + ts;',
    '    var dList = fieldToList(dom);',
    '    return "每月" + listToHuman(dList) + "日 " + ts;',
    '  }',
    '',
    '  // Day-of-week with range (already mostly handled, catch remaining)',
    '  if (dom !== "*" && month === "*" && dow !== "*") {',
    '    var dList2 = fieldToList(dom);',
    '    var dowList2 = fieldToList(dow);',
    '    return "每月" + listToHuman(dList2) + "日 每" + listToHuman(dowList2, DOW_NAMES) + " " + ts;',
    '  }',
    '',
    '  return expr;',
    '}',
    '',
    'function isOnceTask(t) {',
    '  return t.cron_expr && t.cron_expr.indexOf("once:") === 0;',
    '}',
    '',
    'function onceToHuman(expr) {',
    '  if (!expr || expr.indexOf("once:") !== 0) return "";',
    '  var ts = expr.slice(5);',
    '  try {',
    '    var y = ts.slice(0,4), mo = ts.slice(4,6), d = ts.slice(6,8);',
    '    var h = ts.slice(9,11), m = ts.slice(11,13);',
    '    return "一次性 · " + y + "-" + mo + "-" + d + " " + h + ":" + m;',
    '  } catch(e) { return "一次性"; }',
    '}',
    '',
    '// --- data ---',
    'function load() {',
    '  fetch(API + "/tasks").then(function(r){return r.json()}).then(function(data){',
    '    tasks = Array.isArray(data) ? data : [];',
    '    var on = tasks.filter(function(t){return t.enabled && !isOnceTask(t)}).length;',
    '    var off = tasks.filter(function(t){return !t.enabled}).length;',
    '    var oc = tasks.filter(function(t){return t.enabled && isOnceTask(t)}).length;',
    '    document.getElementById("n-on").textContent = on + (oc ? " +" + oc + "一次" : "");',
    '    document.getElementById("n-off").textContent = off;',
    '    document.getElementById("tick").textContent = new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});',
    '    renderCards();',
    '  }).catch(function(e){ console.error(e); });',
    '}',
    '',
    '// --- card rendering ---',
    'function renderCards() {',
    '  var el = document.getElementById("card-grid");',
    '  if (!tasks.length) {',
    '    el.innerHTML = \'<div class="empty"><div class="empty-icon">&#9200;</div><div class="empty-title">暂无定时任务</div><div class="empty-desc">点击右上角「新建任务」创建第一个定时规则</div></div>\';',
    '    return;',
    '  }',
    '  el.innerHTML = tasks.map(function(t){',
    '    var isOnce = isOnceTask(t);',
    '    var sClass = !t.enabled ? "off" : isOnce ? "once" : "on";',
    '    var human = isOnce ? onceToHuman(t.cron_expr) : cronToHuman(t.cron_expr);',
    '    var badgeClass = !t.enabled ? "off" : isOnce ? "once" : "on";',
    '    var badgeText = !t.enabled ? "已停用" : isOnce ? "一次性" : "运行中";',
    '    var icon = isOnce ? "&#9889;" : t.enabled ? "&#128338;" : "&#128164;";',
    '    var nextRun = "";',
    '    if (t.enabled && !isOnce) nextRun = \'<div class="tc-next">下次: <span>\' + esc(human) + \'</span></div>\';',
    '    else if (isOnce) nextRun = \'<div class="tc-next">\' + esc(human) + \' · 执行后自动停用</div>\';',
    '    return \'<div class="tcard \' + sClass + \'">\' +',
    '      \'<div class="tc-top">\' +',
    '        \'<div class="tc-icon">\' + icon + \'</div>\' +',
    '        \'<div class="tc-badges">\' +',
    '          \'<span class="badge badge-\' + badgeClass + \'">\' + badgeText + \'</span>\' +',
    '        \'</div>\' +',
    '      \'</div>\' +',
    '      \'<div class="tc-name">\' + esc(t.name) + \'</div>\' +',
    '      \'<div class="tc-desc">\' + esc(t.description||"") + \'</div>\' +',
    '      \'<div class="tc-sched"><strong>\' + esc(human) + \'</strong></div>\' +',
    '      nextRun +',
    '      \'<div class="tc-actions">\' +',
    '        \'<button class="btn-card go" data-action="run" data-id="\' + t.id + \'">&#9654; 立即执行</button>\' +',
    '        \'<button class="btn-card" data-action="edit" data-id="\' + t.id + \'">&#9998; 编辑</button>\' +',
    '        \'<button class="btn-card" data-action="detail" data-id="\' + t.id + \'">&#128196; 提示词</button>\' +',
    '        \'<button class="btn-card del" data-action="delete" data-id="\' + t.id + \'">&#10005; 删除</button>\' +',
    '      \'</div>\' +',
    '    \'</div>\';',
    '  }).join("");',
    '  // Bind card action buttons',
    '  var btns = el.querySelectorAll(".btn-card[data-action]");',
    '  for (var i = 0; i < btns.length; i++) {',
    '    btns[i].onclick = function(e) {',
    '      e.stopPropagation();',
    '      var action = this.dataset.action;',
    '      var id = parseInt(this.dataset.id, 10);',
    '      if (action === "run") triggerRun(id);',
    '      else if (action === "edit") openForm(id);',
    '      else if (action === "detail") openDetail(id);',
    '      else if (action === "delete") confirmDelete(id);',
    '    };',
    '  }',
    '}',
    '',
    '// --- cron preset engine ---',
    '// --- cron preset engine ---',
    'function detectPreset(cron) {',
    '  if (!cron) return { preset: "daily", h: 9, m: 0 };',
    '  // Once: "once:20260615T170000"',
    '  if (cron.indexOf("once:") === 0) {',
    '    var ts = cron.slice(5);',
    '    var y = ts.slice(0,4), mo = ts.slice(4,6), d = ts.slice(6,8);',
    '    var h2 = ts.slice(9,11), m2 = ts.slice(11,13);',
    '    return { preset: "once", h: parseInt(h2,10)||0, m: parseInt(m2,10)||0, onceDate: y+mo+d, onceHour: h2, onceMin: m2, onceMode: "time" };',
    '  }',
    '  var parts = cron.trim().split(/\\s+/);',
    '  if (parts.length !== 5) return { preset: "custom", h: 9, m: 0, customCron: cron };',
    '  var m = parseInt(parts[0],10), h = parseInt(parts[1],10), dom = parts[2], mon = parts[3], dow = parts[4];',
    '  // Interval: */N * * * *',
    '  var ivMatch = parts[0].match(/^\\*\\/(\\d+)$/);',
    '  if (ivMatch && parts[1] === "*" && dom === "*" && mon === "*" && dow === "*") {',
    '    var n = parseInt(ivMatch[1],10);',
    '    if (n < 60) return { preset: "interval", h: 0, m: 0, intervalN: n, intervalUnit: "min" };',
    '    if (n >= 60 && n < 1440 && n % 60 === 0) return { preset: "interval", h: 0, m: 0, intervalN: n/60, intervalUnit: "hour" };',
    '  }',
    '  var hMatch = parts[1].match(/^\\*\\/(\\d+)$/);',
    '  if (hMatch && parts[0] === "0" && dom === "*" && mon === "*" && dow === "*")',
    '    return { preset: "interval", h: 0, m: 0, intervalN: parseInt(hMatch[1],10), intervalUnit: "hour" };',
    '  if (mon !== "*") return { preset: "custom", h: h, m: m, dom: dom, mon: mon, dow: dow };',
    '  if (dom === "*" && dow === "1-5") return { preset: "workday", h: h, m: m };',
    '  if (dom === "*" && /^[0-7]$/.test(dow)) return { preset: "weekly", h: h, m: m, weekday: parseInt(dow,10) % 7 };',
    '  if (/^\\d+$/.test(dom) && dow === "*") return { preset: "monthly", h: h, m: m, monthDay: parseInt(dom,10) };',
    '  if (dom === "*" && dow === "*") return { preset: "daily", h: h, m: m };',
    '  return { preset: "custom", h: h, m: m, dom: dom, mon: mon, dow: dow };',
    '}',
    '',
    'function buildCronFromForm() {',
    '  var preset = document.getElementById("f-preset").value;',
    '  if (preset === "once") {',
    '    var mode = document.querySelector("input[name=\'once-mode\']:checked").value;',
    '    if (mode === "after") {',
    '      var nn = parseInt(document.getElementById("f-once-n").value,10) || 30;',
    '      var uu = document.getElementById("f-once-unit").value;',
    '      var mins = uu === "hour" ? nn * 60 : nn;',
    '      var target = new Date(Date.now() + mins * 60000);',
    '      var ts = target.getFullYear() +',
    '        String(target.getMonth()+1).padStart(2,"0") +',
    '        String(target.getDate()).padStart(2,"0") + "T" +',
    '        String(target.getHours()).padStart(2,"0") +',
    '        String(target.getMinutes()).padStart(2,"0") + "00";',
    '      return "once:" + ts;',
    '    } else {',
    '      var d = document.getElementById("f-once-date").value;',
    '      var hh = document.getElementById("f-once-hour").value;',
    '      var mm = document.getElementById("f-once-min").value;',
    '      return "once:" + d.replace(/-/g,"") + "T" + hh + mm + "00";',
    '    }',
    '  }',
    '  var h = parseInt(document.getElementById("f-hour").value,10) || 0;',
    '  var m = parseInt(document.getElementById("f-min").value,10) || 0;',
    '  if (preset === "daily")   return m + " " + h + " * * *";',
    '  if (preset === "workday") return m + " " + h + " * * 1-5";',
    '  if (preset === "weekly") {',
    '    var wd = document.getElementById("f-weekday").value;',
    '    return m + " " + h + " * * " + wd;',
    '  }',
    '  if (preset === "monthly") {',
    '    var md = parseInt(document.getElementById("f-monthday").value,10) || 1;',
    '    return m + " " + h + " " + Math.min(28, Math.max(1, md)) + " * *";',
    '  }',
    '  if (preset === "interval") {',
    '    var n = parseInt(document.getElementById("f-ival-n").value,10) || 5;',
    '    var unit = document.getElementById("f-ival-unit").value;',
    '    if (unit === "min")  return "*/" + n + " * * * *";',
    '    if (unit === "hour") return "0 */" + n + " * * *";',
    '    return "*/5 * * * *";',
    '  }',
    '  if (preset === "custom") {',
    '    var cm = document.getElementById("fc-minute").value;',
    '    var ch = document.getElementById("fc-hour").value;',
    '    var cd = getCbFieldValue("fc-dom", 1, 31);',
    '    var cmo = getCbFieldValue("fc-month", 1, 12);',
    '    var cw = getCbFieldValue("fc-dow", 0, 6);',
    '    return cm + " " + ch + " " + cd + " " + cmo + " " + cw;',
    '  }',
    '  return m + " " + h + " * * *";',
    '}',
    '',
    'function selectPreset(preset) {',
    '  document.getElementById("f-preset").value = preset;',
    '  var btns = document.querySelectorAll(".preset-btn");',
    '  for (var i = 0; i < btns.length; i++) btns[i].classList.toggle("sel", btns[i].dataset.preset === preset);',
    '  var isTimed = (preset === "daily" || preset === "workday" || preset === "weekly" || preset === "monthly");',
    '  document.getElementById("time-row").style.display = isTimed ? "flex" : "none";',
    '  document.getElementById("weekday-row").style.display = preset === "weekly" ? "flex" : "none";',
    '  document.getElementById("monthday-row").style.display = preset === "monthly" ? "flex" : "none";',
    '  document.getElementById("interval-row").style.display = preset === "interval" ? "flex" : "none";',
    '  document.getElementById("once-row").style.display = preset === "once" ? "block" : "none";',
    '  document.getElementById("custom-row").style.display = preset === "custom" ? "block" : "none";',
    '  if (preset === "once") updateOncePreview();',
    '  if (preset === "custom") updateCustomPreview();',
    '}',
    '',
    'function updateCustomPreview() {',
    '  var el = document.getElementById("custom-preview");',
    '  if (!el) return;',
    '  var cm = document.getElementById("fc-minute").value;',
    '  var ch = document.getElementById("fc-hour").value;',
    '  var cd = getCbFieldValue("fc-dom", 1, 31);',
    '  var cmo = getCbFieldValue("fc-month", 1, 12);',
    '  var cw = getCbFieldValue("fc-dow", 0, 6);',
    '  var cron = cm + " " + ch + " " + cd + " " + cmo + " " + cw;',
    '  el.innerHTML = \'<span class="human">\' + cronToHuman(cron) + \'</span> <code style="font-size:9px;color:var(--text3)">\' + cron + \'</code>\';',
    '}',
    '',
    'function updateOncePreview() {',
    '  var el = document.getElementById("once-preview");',
    '  if (!el) return;',
    '  var mode = document.querySelector("input[name=\'once-mode\']:checked").value;',
    '  if (mode === "after") {',
    '    var n = document.getElementById("f-once-n").value || "30";',
    '    var u = document.getElementById("f-once-unit").value;',
    '    el.textContent = n + " " + (u === "hour" ? "小时" : "分钟") + "后执行一次";',
    '  } else {',
    '    var d = document.getElementById("f-once-date").value;',
    '    var hh = document.getElementById("f-once-hour").value;',
    '    var mm = document.getElementById("f-once-min").value;',
    '    el.textContent = d + " " + hh + ":" + mm + " 执行一次";',
    '  }',
    '}',
    '',
    '// --- cron field parse & compress ---',
    'function parseCronField(str, min, max) {',
    '  if (!str || str === "*") { var all = []; for (var i = min; i <= max; i++) all.push(i); return all; }',
    '  var result = []; var parts = str.split(",");',
    '  for (var p = 0; p < parts.length; p++) {',
    '    var part = parts[p];',
    '    if (part.indexOf("-") >= 0) {',
    '      var range = part.split("-"); var a = parseInt(range[0],10), b = parseInt(range[1],10);',
    '      for (var i = a; i <= b; i++) { if (result.indexOf(i) < 0) result.push(i); }',
    '    } else {',
    '      var v = parseInt(part,10); if (result.indexOf(v) < 0) result.push(v);',
    '    }',
    '  }',
    '  return result;',
    '}',
    '',
    'function compressRanges(vals, min, max) {',
    '  if (!vals || !vals.length) return "*";',
    '  var sorted = vals.slice().sort(function(a,b){return a-b;});',
    '  if (sorted.length === (max - min + 1)) return "*";',
    '  var parts = []; var i = 0;',
    '  while (i < sorted.length) {',
    '    var start = sorted[i]; var end = start;',
    '    while (i + 1 < sorted.length && sorted[i + 1] === end + 1) { end = sorted[++i]; }',
    '    if (end - start >= 2) parts.push(start + "-" + end);',
    '    else if (end > start) parts.push(start + "," + end);',
    '    else parts.push(String(start));',
    '    i++;',
    '  }',
    '  return parts.join(",");',
    '}',
    '',
    'function getCbFieldValue(containerId, min, max) {',
    '  var el = document.getElementById(containerId);',
    '  if (!el) return "*";',
    '  if (el.tagName === "SELECT") return el.value;',
    '  var cbs = el.querySelectorAll("input[type=\'checkbox\']:checked");',
    '  if (cbs.length === 0) return "*";',
    '  var vals = [];',
    '  for (var i = 0; i < cbs.length; i++) { vals.push(parseInt(cbs[i].value,10)); }',
    '  return compressRanges(vals, min, max);',
    '}',
    '',
    '// Custom cron field dropdown (minute/hour keep select)',
    'function cronFieldOpts(min, max, sel) {',
    '  var s = \'<option value="*">*</option>\';',
    '  for (var i = min; i <= max; i++) { s += \'<option value="\' + i + \'"\' + (i === sel ? " selected" : "") + \'>\' + String(i).padStart(2,"0") + \'</option>\'; }',
    '  return s;',
    '}',
    '',
    '// --- checkbox grid generators ---',
    'function domCbGrid(sel, min, max) {',
    '  var checked = parseCronField(sel, min, max);',
    '  var s = \'<div class="cb-quick"><button type="button" class="cbq-btn" data-target="fc-dom" data-set="all">全选</button><button type="button" class="cbq-btn" data-target="fc-dom" data-set="none">清空</button></div>\';',
    '  s += \'<div class="cb-items cb-dom">\';',
    '  for (var i = min; i <= max; i++) {',
    '    s += \'<label class="cbi cbi-dom"><input type="checkbox" value="\' + i + \'"\' + (checked.indexOf(i) >= 0 ? " checked" : "") + \'><span>\' + i + \'</span></label>\';',
    '  }',
    '  s += \'</div>\'; return s;',
    '}',
    '',
    'function monthCbGrid(sel) {',
    '  var checked = parseCronField(sel, 1, 12);',
    '  var s = \'<div class="cb-quick"><button type="button" class="cbq-btn" data-target="fc-month" data-set="1,4,7,10">每季度</button><button type="button" class="cbq-btn" data-target="fc-month" data-set="1,2,3,4,5,6">上半年</button><button type="button" class="cbq-btn" data-target="fc-month" data-set="7,8,9,10,11,12">下半年</button><button type="button" class="cbq-btn" data-target="fc-month" data-set="all">全年</button></div>\';',
    '  s += \'<div class="cb-items cb-months">\';',
    '  for (var i = 1; i <= 12; i++) {',
    '    s += \'<label class="cbi"><input type="checkbox" value="\' + i + \'"\' + (checked.indexOf(i) >= 0 ? " checked" : "") + \'><span>\' + i + \'月</span></label>\';',
    '  }',
    '  s += \'</div>\'; return s;',
    '}',
    '',
    'function dowCbGrid(sel) {',
    '  var checked = parseCronField(sel, 0, 6);',
    '  var dn = ["日","一","二","三","四","五","六"];',
    '  var s = \'<div class="cb-quick"><button type="button" class="cbq-btn" data-target="fc-dow" data-set="1,2,3,4,5">工作日</button><button type="button" class="cbq-btn" data-target="fc-dow" data-set="0,6">周末</button><button type="button" class="cbq-btn" data-target="fc-dow" data-set="all">每天</button></div>\';',
    '  s += \'<div class="cb-items cb-dow">\';',
    '  for (var i = 0; i < 7; i++) {',
    '    s += \'<label class="cbi"><input type="checkbox" value="\' + i + \'"\' + (checked.indexOf(i) >= 0 ? " checked" : "") + \'><span>\' + dn[i] + \'</span></label>\';',
    '  }',
    '  s += \'</div>\'; return s;',
    '}',
    '',
    '// --- form ---',
    'function openForm(id) {',
    '  editingTask = id ? tasks.find(function(t){return t.id === id}) : null;',
    '  var t = editingTask || {};',
    '  var cv = t.cron_expr || "";',
    '  var ps = detectPreset(cv);',
    '  var to = t.timeout_sec || 300;',
    '',
    '  document.getElementById("form-title").textContent = editingTask ? "编辑任务" : "新建任务";',
    '',
    '  var presetKeys = ["daily","workday","weekly","monthly","interval","once","custom"];',
    '  var presetLabels = {daily:"每天",workday:"工作日",weekly:"每周",monthly:"每月",interval:"间隔",once:"一次性",custom:"自定义"};',
    '  var presetBtns = presetKeys.map(function(p){',
    '    return \'<button class="preset-btn\' + (ps.preset === p ? " sel" : "") + \'" data-preset="\' + p + \'">\' + presetLabels[p] + \'</button>\';',
    '  }).join("");',
    '',
    '  var weekdayBtns = DAY_KEYS.map(function(d){',
    '    return \'<button class="sub-btn\' + (ps.weekday === d ? " sel" : "") + \'" data-wd="\' + d + \'">\' + DAY_NAMES[d] + \'</button>\';',
    '  }).join("");',
    '',
    '  var timedDisplay = (ps.preset === "daily" || ps.preset === "workday" || ps.preset === "weekly" || ps.preset === "monthly") ? "flex" : "none";',
    '  var weekDisplay = ps.preset === "weekly" ? "flex" : "none";',
    '  var monthDisplay = ps.preset === "monthly" ? "flex" : "none";',
    '  var ivalDisplay = ps.preset === "interval" ? "flex" : "none";',
    '  var onceDisplay = ps.preset === "once" ? "block" : "none";',
    '  var customDisplay = ps.preset === "custom" ? "block" : "none";',
    '',
    '  // Build date options for once',
    '  var today = new Date();',
    '  var todayStr = today.getFullYear() + "-" + String(today.getMonth()+1).padStart(2,"0") + "-" + String(today.getDate()).padStart(2,"0");',
    '  var tomorrow = new Date(today); tomorrow.setDate(today.getDate()+1);',
    '  var tomorrowStr = tomorrow.getFullYear() + "-" + String(tomorrow.getMonth()+1).padStart(2,"0") + "-" + String(tomorrow.getDate()).padStart(2,"0");',
    '  var onceDateDefault = ps.onceDate ? (ps.onceDate.slice(0,4) + "-" + ps.onceDate.slice(4,6) + "-" + ps.onceDate.slice(6,8)) : todayStr;',
    '  var onceModeChecked = (ps.onceMode || "after") === "after";',
    '  var onceHour = ps.onceHour || String(today.getHours()).padStart(2,"0");',
    '  var onceMin = ps.onceMin || "00";',
    '',
    '  document.getElementById("form-body").innerHTML =',
    '    \'<input type="hidden" id="f-preset" value="\' + ps.preset + \'">\' +',
    '',
    '    \'<div class="fg">\' +',
    '      \'<label class="fl">任务名称</label>\' +',
    '      \'<input class="fi" id="f-name" value="\' + escAttr(t.name||"") + \'" placeholder="例如：每日AI信号日报">\' +',
    '      \'<div class="fhint">起个好记的名字，在定时卡片上显示</div>\' +',
    '    \'</div>\' +',
    '',
    '    \'<div class="fg">\' +',
    '      \'<label class="fl">简介 <span style="font-weight:400;color:var(--text3)">（选填）</span></label>\' +',
    '      \'<input class="fi" id="f-desc" value="\' + escAttr(t.description||"") + \'" placeholder="一句话说清这个任务是干什么的">\' +',
    '      \'<div class="fhint">在卡片上展示，帮人和 AI 快速理解任务用途</div>\' +',
    '    \'</div>\' +',
    '',
    '    \'<div class="fg">\' +',
    '      \'<label class="fl">执行频率</label>\' +',
    '      \'<div class="preset-row" id="preset-row">\' + presetBtns + \'</div>\' +',
    '',
    '      // Time row (for daily/workday/weekly/monthly)',
    '      \'<div class="time-row" id="time-row" style="display:\' + timedDisplay + \'">\' +',
    '        \'<span style="font-size:12px;color:var(--text3)">时间</span>\' +',
    '        \'<input class="time-inp" id="f-hour" type="number" min="0" max="23" value="\' + ps.h + \'">\' +',
    '        \'<span style="font-size:14px;color:var(--text2)">:</span>\' +',
    '        \'<input class="time-inp" id="f-min" type="number" min="0" max="59" value="\' + String(ps.m).padStart(2,"0") + \'">\' +',
    '        \'<span style="font-size:10px;color:var(--text3)">24小时制</span>\' +',
    '      \'</div>\' +',
    '',
    '      // Weekday row',
    '      \'<div class="sub-row" id="weekday-row" style="display:\' + weekDisplay + \'">\' +',
    '        \'<input type="hidden" id="f-weekday" value="\' + (ps.weekday !== undefined ? ps.weekday : 1) + \'">\' +',
    '        weekdayBtns +',
    '      \'</div>\' +',
    '',
    '      // Month day row',
    '      \'<div class="time-row" id="monthday-row" style="display:\' + monthDisplay + \'">\' +',
    '        \'<span style="font-size:12px;color:var(--text3)">每月</span>\' +',
    '        \'<input class="time-inp" id="f-monthday" type="number" min="1" max="28" value="\' + (ps.monthDay||1) + \'">\' +',
    '        \'<span style="font-size:12px;color:var(--text3)">号</span>\' +',
    '      \'</div>\' +',
    '',
    '      // Interval row',
    '      \'<div class="interval-row" id="interval-row" style="display:\' + ivalDisplay + \'">\' +',
    '        \'<span style="font-size:12px;color:var(--text3)">每</span>\' +',
    '        \'<input class="fi" id="f-ival-n" type="number" min="1" max="1440" value="\' + (ps.intervalN||5) + \'" style="width:70px">\' +',
    '        \'<select class="sel-unit" id="f-ival-unit">\' +',
    '          \'<option value="min"\' + (ps.intervalUnit === "min" ? " selected" : "") + \'>分钟</option>\' +',
    '          \'<option value="hour"\' + (ps.intervalUnit === "hour" ? " selected" : "") + \'>小时</option>\' +',
    '        \'</select>\' +',
    '      \'</div>\' +',
    '',
    '      // Once row',
    '      \'<div id="once-row" style="display:\' + onceDisplay + \'">\' +',
    '        \'<div class="once-mode-row">\' +',
    '          \'<label><input type="radio" name="once-mode" value="after"\' + (onceModeChecked ? " checked" : "") + \'> N分钟后</label>\' +',
    '          \'<label><input type="radio" name="once-mode" value="time"\' + (!onceModeChecked ? " checked" : "") + \'> 指定时间</label>\' +',
    '        \'</div>\' +',
    '        \'<div class="interval-row" id="once-after-row" style="display:\' + (onceModeChecked ? "flex" : "none") + \'">\' +',
    '          \'<input class="fi" id="f-once-n" type="number" min="1" max="1440" value="\' + (ps.onceN||30) + \'" style="width:70px">\' +',
    '          \'<select class="sel-unit" id="f-once-unit">\' +',
    '            \'<option value="min"\' + (!ps.onceUnit || ps.onceUnit === "min" ? " selected" : "") + \'>分钟</option>\' +',
    '            \'<option value="hour"\' + (ps.onceUnit === "hour" ? " selected" : "") + \'>小时</option>\' +',
    '          \'</select>\' +',
    '        \'</div>\' +',
    '        \'<div class="time-row" id="once-time-row" style="display:\' + (!onceModeChecked ? "flex" : "none") + \'">\' +',
    '          \'<select class="sel-unit" id="f-once-date"><option value="\' + todayStr + \'" selected>今天</option><option value="\' + tomorrowStr + \'">明天</option></select>\' +',
    '          \'<input class="time-inp" id="f-once-hour" type="number" min="0" max="23" value="\' + onceHour + \'">\' +',
    '          \'<span>:</span>\' +',
    '          \'<input class="time-inp" id="f-once-min" type="number" min="0" max="59" value="\' + onceMin + \'">\' +',
    '        \'</div>\' +',
    '        \'<div class="fhint" id="once-preview" style="color:var(--once);font-weight:500"></div>\' +',
    '      \'</div>\' +',
    '',
    '      // Custom row',
    '      \'<div id="custom-row" style="display:\' + customDisplay + \'">\' +',
    '        \'<div style="display:flex;gap:8px;align-items:center;margin-bottom:14px">\' +',
    '          \'<span style="font-size:11px;color:var(--text2);font-weight:500">分</span><select class="sel-unit" id="fc-minute" style="min-width:62px">\' + cronFieldOpts(0,59,ps.m) + \'</select>\' +',
    '          \'<span style="font-size:11px;color:var(--text2);font-weight:500;margin-left:4px">时</span><select class="sel-unit" id="fc-hour" style="min-width:62px">\' + cronFieldOpts(0,23,ps.h) + \'</select>\' +',
    '          \'<span style="font-size:10px;color:var(--text3);margin-left:4px">24小时制</span>\' +',
    '        \'</div>\' +',
    '        \'<div class="cb-field">\' +',
    '          \'<div class="cb-label">每月哪天</div>\' +',
    '          \'<div class="cb-grid" id="fc-dom">\' + domCbGrid(ps.dom||"*", 1, 31) + \'</div>\' +',
    '        \'</div>\' +',
    '        \'<div class="cb-field">\' +',
    '          \'<div class="cb-label">哪几个月</div>\' +',
    '          \'<div class="cb-grid" id="fc-month">\' + monthCbGrid(ps.mon||"*") + \'</div>\' +',
    '        \'</div>\' +',
    '        \'<div class="cb-field">\' +',
    '          \'<div class="cb-label">每周哪天</div>\' +',
    '          \'<div class="cb-grid" id="fc-dow">\' + dowCbGrid(ps.dow||"*") + \'</div>\' +',
    '        \'</div>\' +',
    '        \'<div class="cb-hint">日和星期互斥：设了具体日期就不要再设星期（cron 会按"或"处理，非预期行为）</div>\' +',
    '        \'<div class="fhint" id="custom-preview"></div>\' +',
    '        \'<div class="fhint" style="margin-top:6px;font-family:var(--mono);font-size:10px;color:var(--text3)">格式: 分 时 日 月 周 | AI可直写此格式到 cron_expr 字段</div>\' +',
    '      \'</div>\' +',
    '    \'</div>\' +',
    '',
    '    \'<input type="hidden" id="f-timeout" value="\' + to + \'">\' +',
    '',
    '    \'<div class="fg">\' +',
    '      \'<label class="fl">提示词</label>\' +',
    '      \'<textarea class="fi" id="f-prompt" placeholder="定时触发时 AI 收到的完整指令。写清楚：要什么、什么格式、多长">\' + escAttr(t.prompt||"") + \'</textarea>\' +',
    '      \'<div class="fhint">AI 在指定时间收到这段文字并开始执行</div>\' +',
    '    \'</div>\' +',
    '',
    '    \'<div class="fg">\' +',
    '      \'<label class="fl">启用</label>\' +',
    '      \'<label class="toggle">\' +',
    '        \'<input type="checkbox" id="f-enabled" \' + (t.enabled !== 0 ? "checked" : "") + \'>\' +',
    '        \'<span class="toggle-track\' + (t.enabled !== 0 ? " on" : "") + \'" id="toggle-track"></span>\' +',
    '        \'<span class="toggle-label" id="toggle-label">\' + (t.enabled !== 0 ? "启用" : "停用") + \'</span>\' +',
    '      \'</label>\' +',
    '      \'<div class="fhint">关闭后任务保留但不会自动触发，仍可手动"立即执行"</div>\' +',
    '    \'</div>\' +',
    '',
    '    \'<div class="fbtns">\' +',
    '      \'<button class="btn-cancel" id="btn-cancel">取消</button>\' +',
    '      \'<button class="btn-submit" id="btn-submit">\' + (editingTask ? "保存" : "添加任务") + \'</button>\' +',
    '    \'</div>\';',
    '',
    '  // --- bind events ---',
    '',
    '  // Preset buttons',
    '  var pbtns = document.querySelectorAll("#preset-row .preset-btn");',
    '  for (var i = 0; i < pbtns.length; i++) {',
    '    pbtns[i].onclick = function(){ selectPreset(this.dataset.preset); };',
    '  }',
    '',
    '  // Weekday buttons',
    '  var wbtns = document.querySelectorAll("#weekday-row .sub-btn");',
    '  for (var i = 0; i < wbtns.length; i++) {',
    '    wbtns[i].onclick = function(){',
    '      document.getElementById("f-weekday").value = this.dataset.wd;',
    '      selectPreset("weekly");',
    '      var siblings = this.parentNode.querySelectorAll(".sub-btn");',
    '      for (var j = 0; j < siblings.length; j++) siblings[j].classList.remove("sel");',
    '      this.classList.add("sel");',
    '    };',
    '  }',
    '',
    '  // Time inputs',
    '  if (document.getElementById("f-hour")) document.getElementById("f-hour").onchange = function(){ selectPreset(document.getElementById("f-preset").value); };',
    '  if (document.getElementById("f-min")) document.getElementById("f-min").onchange = function(){ selectPreset(document.getElementById("f-preset").value); };',
    '  if (document.getElementById("f-monthday")) document.getElementById("f-monthday").onchange = function(){ selectPreset("monthly"); };',
    '  if (document.getElementById("f-ival-n")) document.getElementById("f-ival-n").onchange = function(){ selectPreset("interval"); };',
    '  if (document.getElementById("f-ival-unit")) document.getElementById("f-ival-unit").onchange = function(){ selectPreset("interval"); };',
    '',
    '  // Once mode toggle',
    '  var onceRadios = document.querySelectorAll("input[name=\'once-mode\']");',
    '  for (var i = 0; i < onceRadios.length; i++) {',
    '    onceRadios[i].onchange = function() {',
    '      var isAfter = this.value === "after";',
    '      document.getElementById("once-after-row").style.display = isAfter ? "flex" : "none";',
    '      document.getElementById("once-time-row").style.display = isAfter ? "none" : "flex";',
    '      updateOncePreview();',
    '    };',
    '  }',
    '',
    '  // Once inputs',
    '  var onceN = document.getElementById("f-once-n");',
    '  if (onceN) onceN.onchange = function(){ selectPreset("once"); updateOncePreview(); };',
    '  var onceU = document.getElementById("f-once-unit");',
    '  if (onceU) onceU.onchange = function(){ updateOncePreview(); };',
    '  var onceH = document.getElementById("f-once-hour");',
    '  if (onceH) onceH.onchange = function(){ updateOncePreview(); };',
    '  var onceM = document.getElementById("f-once-min");',
    '  if (onceM) onceM.onchange = function(){ updateOncePreview(); };',
    '  var onceD = document.getElementById("f-once-date");',
    '  if (onceD) onceD.onchange = function(){ updateOncePreview(); };',
    '',
    '  // Custom cron fields',
    '  var fcMin = document.getElementById("fc-minute"); if (fcMin) fcMin.onchange = function(){ updateCustomPreview(); };',
    '  var fcHour = document.getElementById("fc-hour"); if (fcHour) fcHour.onchange = function(){ updateCustomPreview(); };',
    '  var cbGrids = document.querySelectorAll(".cb-grid");',
    '  for (var gi = 0; gi < cbGrids.length; gi++) {',
    '    cbGrids[gi].addEventListener("change", function(){ updateCustomPreview(); });',
    '  }',
    '  var qbtns = document.querySelectorAll(".cbq-btn");',
    '  for (var qi = 0; qi < qbtns.length; qi++) {',
    '    qbtns[qi].onclick = function(e){',
    '      e.preventDefault();',
    '      var target = document.getElementById(this.dataset.target);',
    '      if (!target) return;',
    '      var setVal = this.dataset.set;',
    '      var cbs = target.querySelectorAll("input[type=\'checkbox\']");',
    '      if (setVal === "all") { for (var j = 0; j < cbs.length; j++) cbs[j].checked = true; }',
    '      else if (setVal === "none") { for (var j = 0; j < cbs.length; j++) cbs[j].checked = false; }',
    '      else {',
    '        var vals = setVal.split(",").map(function(v){return parseInt(v,10);});',
    '        for (var j = 0; j < cbs.length; j++) { cbs[j].checked = vals.indexOf(parseInt(cbs[j].value,10)) >= 0; }',
    '      }',
    '      updateCustomPreview();',
    '    };',
    '  }',
    '  if (ps.preset === "custom") updateCustomPreview();',
    '  if (ps.preset === "once") updateOncePreview();',
    '',
    '  // Toggle',
    '  var track = document.getElementById("toggle-track");',
    '  var check = document.getElementById("f-enabled");',
    '  var label = document.getElementById("toggle-label");',
    '  if (track) track.onclick = function(e){',
    '    check.checked = !check.checked;',
    '    track.className = "toggle-track" + (check.checked ? " on" : "");',
    '    label.textContent = check.checked ? "启用" : "停用";',
    '    e.stopPropagation();',
    '  };',
    '',
    '  // Cancel / Submit',
    '  document.getElementById("btn-cancel").onclick = function(){ closeForm(); };',
    '  document.getElementById("btn-submit").onclick = function(){ submitForm(); };',
    '',
    '  document.getElementById("form-overlay").classList.add("show");',
    '}',
    '',
    'function closeForm() {',
    '  document.getElementById("form-overlay").classList.remove("show");',
    '  editingTask = null;',
    '}',
    '',
    'function submitForm() {',
    '  var cronExpr = buildCronFromForm();',
    '  var preset = document.getElementById("f-preset").value;',
    '  var data = {',
    '    name: document.getElementById("f-name").value.trim(),',
    '    project_id: "_", project_dir: "_",',
    '    cron_expr: cronExpr,',
    '    prompt: document.getElementById("f-prompt").value.trim(),',
    '    description: document.getElementById("f-desc").value.trim(),',
    '    timeout_sec: parseInt(document.getElementById("f-timeout").value,10) || 300,',
    '    enabled: document.getElementById("f-enabled").checked ? 1 : 0',
    '  };',
    '  if (!data.name || !data.prompt) {',
    '    alert("任务名称和提示词为必填项");',
    '    return;',
    '  }',
    '  var url = editingTask ? API + "/tasks/" + editingTask.id : API + "/tasks";',
    '  fetch(url, {',
    '    method: editingTask ? "PUT" : "POST",',
    '    headers: {"Content-Type":"application/json"},',
    '    body: JSON.stringify(data)',
    '  }).then(function(res){',
    '    if (!res.ok) return res.json().then(function(e){ alert("保存失败: " + (e.error||"")); });',
    '    if (!editingTask) res.json().then(function(c){ load(); });',
    '    else { closeForm(); load(); }',
    '  });',
    '}',
    '',
    '// --- actions ---',
    'function triggerRun(id) { fetch(API + "/tasks/" + id + "/run",{method:"POST"}); setTimeout(load,1500); }',
    '',
    'function confirmDelete(id) {',
    '  confirmDeleteId = id;',
    '  document.getElementById("cfm-overlay").classList.add("show");',
    '  document.getElementById("cfm-del-btn").onclick = function(){',
    '    fetch(API + "/tasks/" + confirmDeleteId, {method:"DELETE"}).then(function(){',
    '      confirmDeleteId = null;',
    '      document.getElementById("cfm-overlay").classList.remove("show");',
    '      load();',
    '    });',
    '  };',
    '}',
    '',
    'function openDetail(id) {',
    '  var t = null;',
    '  for (var i = 0; i < tasks.length; i++) { if (tasks[i].id === id) { t = tasks[i]; break; } }',
    '  if (!t) return;',
    '  var isOnce = isOnceTask(t);',
    '  var human = isOnce ? onceToHuman(t.cron_expr) : cronToHuman(t.cron_expr);',
    '  document.getElementById("detail-title").textContent = t.name + " · 提示词";',
    '  document.getElementById("detail-body").innerHTML =',
    '    \'<div class="detail-meta">\' +',
    '      \'<strong>\' + esc(t.name) + \'</strong>\' +',
    '      \'调度: \' + esc(human) + \' · \' + (t.enabled ? "启用" : "停用") +',
    '      (t.description ? \'<br>\' + esc(t.description) : "") +',
    '    \'</div>\' +',
    '    \'<div class="detail-prompt">\' + esc(t.prompt) + \'</div>\';',
    '  document.getElementById("detail-overlay").classList.add("show");',
    '}',
    '',
    'function closeDetail() { document.getElementById("detail-overlay").classList.remove("show"); }',
    '',
    'function closeConfirm() { confirmDeleteId = null; document.getElementById("cfm-overlay").classList.remove("show"); }',
    '',
    '// --- init ---',
    'document.getElementById("btn-add").onclick = function(){ openForm(); };',
    'document.getElementById("form-close-btn").onclick = function(){ closeForm(); };',
    'document.getElementById("cfm-cancel-btn").onclick = function(){ closeConfirm(); };',
    'document.getElementById("form-overlay").addEventListener("click",function(e){ if(e.target===this) closeForm(); });',
    'document.getElementById("detail-close-btn").onclick = function(){ closeDetail(); };',
    'document.getElementById("detail-overlay").addEventListener("click",function(e){ if(e.target===this) closeDetail(); });',
    'document.getElementById("cfm-overlay").addEventListener("click",function(e){ if(e.target===this) closeConfirm(); });',
    '',
    'load();',
    'setInterval(load, 30000);'
  ].join('\n');
}

module.exports = { render: render };
